version: '3'

services:
  flask:
    build: 
      context: .
      dockerfile: ./devops/Dockerfile
    image: service-nlp
    container_name: service-nlp
    ports:
      - "5000:5000"
    tty: true
    environment:
      FLASK_APP: app.py
    command: flask run --host 0.0.0.0 --port 5000
